version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./Backend/.env.docker
    restart: always
    networks:
      - edustream-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - edustream-network

  web:
    build:
      context: ./Backend
    command: python dist/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/code
      - ./Backend/dist/media:/code/dist/media
      - ./Backend/dist/static:/code/dist/static
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env.docker
    depends_on:
      - db
      - redis
    networks:
      - edustream-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/dist:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000  
    networks:
      - edustream-network
    depends_on:
      - web

volumes:
  postgres_data:

networks:
  edustream-network:
    driver: bridge
